name: webapp-build

on:
  push:
    branches:
      - main
  workflow_dispatch: #Manual Build

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP archive with Build Number
        run: |
          mkdir -p ../artifacts
          zip -r ../artifacts/build-${{ github.run_number }}.zip ./microservice-1a/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Upload ZIP to S3
        run: |
          aws s3 cp ../artifacts/build-${{ github.run_number }}.zip s3://730335198243-deployment/artifacts/build-${{ github.run_number }}.zip
        env:
          AWS_DEFAULT_REGION: sa-east-1