name: build-and-deploy-hml

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.10.5"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image to ECR
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        ECR_REPO_NAME: bff-gateway
        AWS_REGION: us-east-1
        BUILD_ID: ${{ github.run_id }}
      run: |
        # Login to AWS ECR
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        
        # Build and push the image directly to ECR using buildx
        docker buildx build \
          --platform linux/arm64 \
          -t $ECR_REPO_NAME:$BUILD_ID \
          -t $ECR_REPO_NAME:latest \
          --push .

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Build and push Docker image to ECR
    #   env:
    #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    #     ECR_REPO_NAME: bff-gateway
    #     AWS_REGION: us-east-1
    #   run: |
    #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    #     docker buildx build --platform linux/arm64-t $ECR_REPO_NAME .
    #     docker tag $ECR_REPO_NAME:$BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
    #     docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform plan

    # - name: Pause for Manual Approval
    #   uses: chrnorm/deploy-pause@v2
    #   with:
    #     step-name: "Approve Terraform Plan"

    - name: Apply Terraform
      run: terraform apply -var "image_uri=879381271270.dkr.ecr.us-east-1.amazonaws.com/bff-gateway:latest"

    - name: Clean up Docker images
      run: |
        docker rmi $ECR_REPO_NAME:latest
        docker rmi $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
