name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (hml or prd)"
        required: true
        default: hml

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_id.outputs.build_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image to ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPO_NAME: bff-gateway
          AWS_REGION: us-east-1
        id: build_id
        run: |
          BUILD_ID=${{ github.run_id }}
          echo "::set-output name=build_id::$BUILD_ID"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          docker buildx build \
          --platform linux/arm64 \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID \
          --push .

  Deploy HML:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.ref == 'refs/heads/release'
    environment:
      name: hml
      url: https://example.com/${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Initialize Terraform
        run: cd infra/hml && terraform init

      - name: Terraform Apply
        run: cd infra/hml && terraform apply -var "image_uri=879381271270.dkr.ecr.us-east-1.amazonaws.com/bff-gateway:latest"

  Deploy PRD:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.ref == 'refs/heads/main'
    environment:
      name: prd
      url: https://example.com/${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Initialize Terraform
        run: cd infra/prd && terraform init

      - name: Terraform Apply
        run: cd infra/prd && terraform apply -var "image_uri=879381271270.dkr.ecr.us-east-1.amazonaws.com/bff-gateway:latest"
      